### PR TITLE
Add Otter operations from BuildMaster to Otter

### PR DESCRIPTION
**Pull request by BenLubar**
- Otter::Remediate-Drift
- Otter::Set-Variable

### CODE REVIEW

**Comment by apapadimoulis** [comment]
My main hesitation w/ this approach is that it's using the API... which means you'd need to set up a "self connection" to set up on the same instance of Otter.

On the other hand, I do like being able to have multiple otter instances orchestrate eachother. 

Just a thought... but I wonder if, for the Otter operation, we could have a separate tab for "Set on Other Instance" or something like that, where you can specify the credential to do it.

@jrasch  or @gdivis  any thoughts?

**Comment by BenLubar** [comment]
It would be possible to make the operations not require credentials when used on Otter and have no credentials mean "perform action on the currently-running-this-operation instance of Otter".

/cc @jrasch @gdivis @apapadimoulis

**Comment by apapadimoulis** [comment]
@BenLubar we'll get this pushed in the next Otter/BuildMaster releases; can you update the PR so we can merge?

For the Otter Operation, can you make a separate tab for "Set on Other Instance" where you can specify the credential to do it. If not speciifed, it operates on local instance.

**Comment by BenLubar** [comment]
@apapadimoulis Two minor things:

- "Check server drift" doesn't work on Otter without an API key since it can't be done without talking directly to the service. This shouldn't matter since that function is only used by a BuildMaster promotion requirement.
- If no credentials are specified, suggestion providers won't return any results. This was already the case if the credentials were specified in the operation's properties instead of as a named resource credential.

**Comment by apapadimoulis** [comment]
Code looks good to me; @thoven  can you review and merge?

**Pull request merged**
